export const T = {
  ko: {
    title: '성과 대시보드',
    loading: '로딩 중...',
    denied: '접근 권한이 없습니다',
    loadingData: '데이터 불러오는 중...',
    lastUpdate: '마지막 업데이트',
    refresh: '새로고침',
    autoRefresh: '자동',
    today: '오늘 실시간',
    pageViews: '랜딩',
    chart1d: '1일',
    chart3d: '3일',
    chartWeekly: '주간',
    chartMonthly: '월간',
    backTitle: '관리자로 돌아가기',
    trend: '추이',
    kpi: 'KPI',
    funnel: '퍼널',
    intentTitle: '관심도 분포',
    topCompanies: '상위 회사',
    countUnit: '개',
    dailyDetail: '일별 상세',
    weeklyDetail: '주별 상세',
    monthlyDetail: '월별 상세',
    total: '합계',
    expTitle: '실험 / 개선 기록',
    expAdd: '+ 추가',
    expCancel: '취소',
    expStartDate: '실험 시작일',
    expPlaceholder: '예: CTA 문구 변경, 랜딩 리디자인...',
    expSave: '저장',
    expDelete: '삭제',
    expDeleteConfirm: '이 실험 기록을 삭제하시겠습니까?',
    expEmpty: '아직 기록이 없습니다. 실험이나 개선 사항을 추가해보세요.',
    expStatus: '상태',
    expRunning: '진행중',
    expSuccess: '성공',
    expFailure: '실패',
    expEndDate: '종료일',
    expResultNote: '결과 / 사유',
    expResultPlaceholder: '실험 결과나 성공/실패 사유를 기록하세요...',
    expEnd: '실험 종료',
    avg: '평균',
    tableHeaders: ['날짜', '세션', '전체', '광고', '자연유입', '가입', '회사', '홈→Jobs', '공고클릭', 'Jobs페이지뷰', '지원클릭', '스크랩', '이력서', '채용지원'],
    metrics: {
      sessions: '방문 세션', submissions: '연봉 정보 제출', ad: '광고 유입 제출', organic: '자연 유입 제출',
      signups: '신규 가입자', jobClicks: '홈→채용 클릭', cardClicks: '공고 카드 클릭', jobApps: '채용 공고 지원', companies: '연봉 제출 회사 수',
      jobsPageViews: '채용 페이지 조회', applyClicks: '지원 버튼 클릭', saveClicks: '공고 스크랩',
      resumeUploads: '이력서 등록', resumePublic: '이력서 공개', resumePublicApp: '이력서 공개(앱)', resumePublicWeb: '이력서 공개(웹)', cvSuccessApps: 'CV 등록→원탭 지원', jobAppsCompany: '채용 공고 지원(기업등록)',
    },
    funnelEmpty: '스테이지를 클릭하여 퍼널을 구성하세요',
    funnelClear: '초기화',
    funnelOverall: '전체 전환율',
    funnelStep: 'Step',
    funnelDropped: '이탈',
    funnelOf: '전체 대비',
    funnelConv: '전환율',
    users: '가입자',
    usersTitle: '가입자 목록',
    usersTotal: '총 가입자',
    usersDownloadCsv: 'CSV 다운로드',
    usersEmail: '이메일',
    usersName: '이름',
    usersProvider: '가입 방법',
    usersCreatedAt: '가입일',
    usersLastSignIn: '마지막 로그인',
    usersLoading: '가입자 불러오는 중...',
    usersEmpty: '가입자가 없습니다.',
    applications: '지원자',
    appsTitle: '채용 지원 목록',
    appsTotal: '총 지원',
    appsEmpty: '지원 내역이 없습니다.',
    appsLoading: '지원 내역 불러오는 중...',
    appsJob: '포지션',
    appsCompany: '회사',
    appsApplicant: '지원자',
    appsEmail: '이메일',
    appsStatus: '상태',
    appsDate: '지원일',
    appsNote: '메모',
    appsResume: '이력서',
    appsSave: '저장',
    hrApproval: 'HR 승인',
    ga4: 'GA4',
    ga4Sessions: '세션',
    ga4TotalUsers: '전체 사용자',
    ga4NewUsers: '신규 사용자',
    ga4EngagedSessions: '참여 세션',
    ga4BounceRate: '이탈률',
    ga4AvgDuration: '평균 체류시간',
    ga4ByChannel: '채널별',
    ga4ByDevice: '디바이스별',
    ga4LandingPages: '랜딩 페이지별',
    ga4Channel: '채널',
    ga4Page: '페이지',
    utm: 'UTM',
    utmTitle: 'UTM 캠페인 분석',
    utmSource: '소스 (utm_source)',
    utmCampaign: '캠페인 (utm_campaign)',
    utmContent: '콘텐츠 (utm_content)',
    utmViews: '방문',
    utmSubmissions: '제출',
    utmConvRate: '전환율',
    utmTotalViews: '총 UTM 방문',
    utmNoData: 'UTM 데이터가 아직 없습니다. 캠페인 링크로 방문이 들어오면 여기에 표시됩니다.',
    resumes: '이력서',
    talent: '인재풀',
    verifications: '연봉 인증',
    community: '커뮤니티',
    reports: '신고/피드백',
    appMetrics: '앱 지표',
    resumesTitle: '이력서 등록자 목록',
    resumesTotal: '총 등록',
    resumesPublic: '공개',
    resumesSearch: '이름, 이메일, 포지션 검색...',
    resumesFilterAll: '전체',
    resumesFilterPublic: '공개',
    resumesFilterPrivate: '비공개',
    resumesDownloadCsv: 'CSV 다운로드',
    resumesName: '이름',
    resumesEmail: '이메일',
    resumesPosition: '포지션',
    resumesYoe: '경력',
    resumesLocation: '위치',
    resumesUniversity: '학교',
    resumesPublicLabel: '공개여부',
    resumesFile: '파일',
    resumesUpdated: '수정일',
    resumesUnit: '명',
    resumesNote: '* 유저 기준 집계 (동일 유저가 재업로드해도 1명으로 카운트)',
    resumesLoading: '이력서 데이터 불러오는 중...',
    resumesEmpty: '이력서를 등록한 사용자가 없습니다.',
    resumesNoMatch: '검색 결과가 없습니다.',
    retention: '리텐션',
    retentionLoading: '리텐션 데이터 불러오는 중...',
    retentionEmpty: '리텐션 데이터가 없습니다.',
    retentionTotal: '전체 유저',
    retentionWAU: 'WAU (7일)',
    retentionMAU: 'MAU (30일)',
    retentionCohort: '주간 코호트 리텐션',
    retentionWeek: '가입 주차',
    retentionUsers: '가입자',
    retentionNote: '* last_sign_in_at 기준. 가입 후 N주 뒤에도 로그인한 유저 비율.',
  },
  en: {
    title: 'Performance Dashboard',
    loading: 'Loading...',
    denied: 'Access denied',
    loadingData: 'Loading data...',
    lastUpdate: 'Last updated',
    refresh: 'Refresh',
    autoRefresh: 'Auto',
    today: 'Today Live',
    pageViews: 'Landings',
    chart1d: '1D',
    chart3d: '3D',
    chartWeekly: 'W',
    chartMonthly: 'M',
    backTitle: 'Back to Admin',
    trend: 'Trend',
    kpi: 'KPI',
    funnel: 'Funnel',
    intentTitle: 'Intent Breakdown',
    topCompanies: 'Top Companies',
    countUnit: '',
    dailyDetail: 'Daily Detail',
    weeklyDetail: 'Weekly Detail',
    monthlyDetail: 'Monthly Detail',
    total: 'Total',
    expTitle: 'Experiments / Improvements',
    expAdd: '+ Add',
    expCancel: 'Cancel',
    expStartDate: 'Start date',
    expPlaceholder: 'e.g. CTA copy change, landing redesign...',
    expSave: 'Save',
    expDelete: 'Delete',
    expDeleteConfirm: 'Delete this experiment?',
    expEmpty: 'No records yet. Add an experiment or improvement.',
    expStatus: 'Status',
    expRunning: 'Running',
    expSuccess: 'Success',
    expFailure: 'Failure',
    expEndDate: 'End date',
    expResultNote: 'Result / Reason',
    expResultPlaceholder: 'Record the result or reason for success/failure...',
    expEnd: 'End Experiment',
    avg: 'avg',
    tableHeaders: ['Date', 'Sessions', 'Total', 'Ad', 'Organic', 'Sign-ups', 'Companies', 'Home→Jobs', 'Job Clicks', 'Jobs Page Views', 'Apply Clicks', 'Saves', 'Resumes', 'Job Apps'],
    metrics: {
      sessions: 'Visit sessions', submissions: 'Salary submissions', ad: 'Ad submissions', organic: 'Organic submissions',
      signups: 'New sign-ups', jobClicks: 'Home→Jobs clicks', cardClicks: 'Job card clicks', jobApps: 'Job applications', companies: 'Companies w/ data',
      jobsPageViews: 'Jobs page views', applyClicks: 'Apply button clicks', saveClicks: 'Job saves',
      resumeUploads: 'Resume uploads', resumePublic: 'Resumes public', resumePublicApp: 'Resumes public (app)', resumePublicWeb: 'Resumes public (web)', cvSuccessApps: 'CV one-tap apply', jobAppsCompany: 'Job applications (company)',
    },
    funnelEmpty: 'Click stages below to build your funnel',
    funnelClear: 'Clear',
    funnelOverall: 'Overall conversion',
    funnelStep: 'Step',
    funnelDropped: 'Dropped',
    funnelOf: 'of total',
    funnelConv: 'Conversion',
    users: 'Users',
    usersTitle: 'Sign-up Users',
    usersTotal: 'Total Users',
    usersDownloadCsv: 'Download CSV',
    usersEmail: 'Email',
    usersName: 'Name',
    usersProvider: 'Provider',
    usersCreatedAt: 'Signed Up',
    usersLastSignIn: 'Last Sign In',
    usersLoading: 'Loading users...',
    usersEmpty: 'No users found.',
    applications: 'Applications',
    appsTitle: 'Job Applications',
    appsTotal: 'Total',
    appsEmpty: 'No applications yet.',
    appsLoading: 'Loading applications...',
    appsJob: 'Position',
    appsCompany: 'Company',
    appsApplicant: 'Applicant',
    appsEmail: 'Email',
    appsStatus: 'Status',
    appsDate: 'Applied',
    appsNote: 'Note',
    appsResume: 'Resume',
    appsSave: 'Save',
    hrApproval: 'HR Approval',
    ga4: 'GA4',
    ga4Sessions: 'Sessions',
    ga4TotalUsers: 'Total Users',
    ga4NewUsers: 'New Users',
    ga4EngagedSessions: 'Engaged Sessions',
    ga4BounceRate: 'Bounce Rate',
    ga4AvgDuration: 'Avg Duration',
    ga4ByChannel: 'By Channel',
    ga4ByDevice: 'By Device',
    ga4LandingPages: 'Landing Pages',
    ga4Channel: 'Channel',
    ga4Page: 'Page',
    utm: 'UTM',
    utmTitle: 'UTM Campaign Analysis',
    utmSource: 'Source (utm_source)',
    utmCampaign: 'Campaign (utm_campaign)',
    utmContent: 'Content (utm_content)',
    utmViews: 'Views',
    utmSubmissions: 'Submissions',
    utmConvRate: 'Conv. Rate',
    utmTotalViews: 'Total UTM Views',
    utmNoData: 'No UTM data yet. Campaign visits will appear here.',
    resumes: 'Resumes',
    talent: 'Talent Pool',
    verifications: 'Verifications',
    community: 'Community',
    reports: 'Reports',
    appMetrics: 'App Metrics',
    resumesTitle: 'Resume Uploads',
    resumesTotal: 'Total',
    resumesPublic: 'Public',
    resumesSearch: 'Search name, email, position...',
    resumesFilterAll: 'All',
    resumesFilterPublic: 'Public',
    resumesFilterPrivate: 'Private',
    resumesDownloadCsv: 'Download CSV',
    resumesName: 'Name',
    resumesEmail: 'Email',
    resumesPosition: 'Position',
    resumesYoe: 'YoE',
    resumesLocation: 'Location',
    resumesUniversity: 'University',
    resumesPublicLabel: 'Visibility',
    resumesFile: 'File',
    resumesUpdated: 'Updated',
    resumesUnit: '',
    resumesNote: '* Counted per user (re-uploads by the same user count as 1)',
    resumesLoading: 'Loading resumes...',
    resumesEmpty: 'No users have uploaded resumes yet.',
    resumesNoMatch: 'No matching results.',
    retention: 'Retention',
    retentionLoading: 'Loading retention data...',
    retentionEmpty: 'No retention data available.',
    retentionTotal: 'Total Users',
    retentionWAU: 'WAU (7D)',
    retentionMAU: 'MAU (30D)',
    retentionCohort: 'Weekly Cohort Retention',
    retentionWeek: 'Signup Week',
    retentionUsers: 'Users',
    retentionNote: '* Based on last_sign_in_at. Percentage of users who logged in again N weeks after signup.',
  },
  vi: {
    title: 'Bảng điều khiển hiệu suất',
    loading: 'Đang tải...',
    denied: 'Không có quyền truy cập',
    loadingData: 'Đang tải dữ liệu...',
    lastUpdate: 'Cập nhật lần cuối',
    refresh: 'Làm mới',
    autoRefresh: 'Tự động',
    today: 'Hôm nay (trực tiếp)',
    pageViews: 'Trang đích',
    chart1d: '1 ngày',
    chart3d: '3 ngày',
    chartWeekly: 'Tuần',
    chartMonthly: 'Tháng',
    backTitle: 'Về trang quản trị',
    trend: 'Xu hướng',
    kpi: 'KPI',
    funnel: 'Phễu',
    intentTitle: 'Phân bố mức độ quan tâm',
    topCompanies: 'Công ty hàng đầu',
    countUnit: '',
    dailyDetail: 'Chi tiết theo ngày',
    weeklyDetail: 'Chi tiết theo tuần',
    monthlyDetail: 'Chi tiết theo tháng',
    total: 'Tổng',
    expTitle: 'Thử nghiệm / Cải tiến',
    expAdd: '+ Thêm',
    expCancel: 'Hủy',
    expStartDate: 'Ngày bắt đầu',
    expPlaceholder: 'VD: đổi nội dung CTA, thiết kế lại trang đích...',
    expSave: 'Lưu',
    expDelete: 'Xóa',
    expDeleteConfirm: 'Xóa bản ghi thử nghiệm này?',
    expEmpty: 'Chưa có bản ghi nào. Hãy thêm một thử nghiệm hoặc cải tiến.',
    expStatus: 'Trạng thái',
    expRunning: 'Đang chạy',
    expSuccess: 'Thành công',
    expFailure: 'Thất bại',
    expEndDate: 'Ngày kết thúc',
    expResultNote: 'Kết quả / Lý do',
    expResultPlaceholder: 'Ghi lại kết quả hoặc lý do thành công/thất bại...',
    expEnd: 'Kết thúc thử nghiệm',
    avg: 'TB',
    tableHeaders: ['Ngày', 'Phiên', 'Tổng', 'Quảng cáo', 'Tự nhiên', 'Đăng ký', 'Công ty', 'Trang chủ→Việc làm', 'Click tin', 'Lượt xem trang việc làm', 'Click ứng tuyển', 'Lưu tin', 'CV', 'Đơn ứng tuyển'],
    metrics: {
      sessions: 'Phiên truy cập', submissions: 'Lượt gửi thông tin lương', ad: 'Lượt gửi từ quảng cáo', organic: 'Lượt gửi tự nhiên',
      signups: 'Đăng ký mới', jobClicks: 'Click Trang chủ→Việc làm', cardClicks: 'Click thẻ tin tuyển dụng', jobApps: 'Đơn ứng tuyển', companies: 'Số công ty có dữ liệu lương',
      jobsPageViews: 'Lượt xem trang việc làm', applyClicks: 'Click nút ứng tuyển', saveClicks: 'Lưu tin tuyển dụng',
      resumeUploads: 'CV đã đăng', resumePublic: 'CV công khai', resumePublicApp: 'CV công khai (app)', resumePublicWeb: 'CV công khai (web)', cvSuccessApps: 'Đăng CV→ứng tuyển 1 chạm', jobAppsCompany: 'Đơn ứng tuyển (tin công ty đăng)',
    },
    funnelEmpty: 'Nhấp vào các bước bên dưới để tạo phễu',
    funnelClear: 'Xóa',
    funnelOverall: 'Tỷ lệ chuyển đổi tổng',
    funnelStep: 'Bước',
    funnelDropped: 'Rời bỏ',
    funnelOf: 'trên tổng',
    funnelConv: 'Tỷ lệ chuyển đổi',
    users: 'Người dùng',
    usersTitle: 'Danh sách đăng ký',
    usersTotal: 'Tổng người dùng',
    usersDownloadCsv: 'Tải CSV',
    usersEmail: 'Email',
    usersName: 'Tên',
    usersProvider: 'Phương thức đăng ký',
    usersCreatedAt: 'Ngày đăng ký',
    usersLastSignIn: 'Đăng nhập gần nhất',
    usersLoading: 'Đang tải người dùng...',
    usersEmpty: 'Không có người dùng.',
    applications: 'Ứng viên',
    appsTitle: 'Danh sách đơn ứng tuyển',
    appsTotal: 'Tổng đơn',
    appsEmpty: 'Chưa có đơn ứng tuyển.',
    appsLoading: 'Đang tải đơn ứng tuyển...',
    appsJob: 'Vị trí',
    appsCompany: 'Công ty',
    appsApplicant: 'Ứng viên',
    appsEmail: 'Email',
    appsStatus: 'Trạng thái',
    appsDate: 'Ngày ứng tuyển',
    appsNote: 'Ghi chú',
    appsResume: 'CV',
    appsSave: 'Lưu',
    hrApproval: 'HR duyệt',
    ga4: 'GA4',
    ga4Sessions: 'Phiên',
    ga4TotalUsers: 'Tổng người dùng',
    ga4NewUsers: 'Người dùng mới',
    ga4EngagedSessions: 'Phiên tương tác',
    ga4BounceRate: 'Tỷ lệ thoát',
    ga4AvgDuration: 'Thời lượng TB',
    ga4ByChannel: 'Theo kênh',
    ga4ByDevice: 'Theo thiết bị',
    ga4LandingPages: 'Theo trang đích',
    ga4Channel: 'Kênh',
    ga4Page: 'Trang',
    utm: 'UTM',
    utmTitle: 'Phân tích chiến dịch UTM',
    utmSource: 'Nguồn (utm_source)',
    utmCampaign: 'Chiến dịch (utm_campaign)',
    utmContent: 'Nội dung (utm_content)',
    utmViews: 'Lượt truy cập',
    utmSubmissions: 'Lượt gửi',
    utmConvRate: 'Tỷ lệ chuyển đổi',
    utmTotalViews: 'Tổng truy cập UTM',
    utmNoData: 'Chưa có dữ liệu UTM. Lượt truy cập từ link chiến dịch sẽ hiển thị tại đây.',
    resumes: 'CV',
    talent: 'Nguồn ứng viên',
    verifications: 'Xác minh lương',
    community: 'Cộng đồng',
    reports: 'Báo cáo/Phản hồi',
    appMetrics: 'Chỉ số app',
    resumesTitle: 'Danh sách người đăng CV',
    resumesTotal: 'Tổng đăng',
    resumesPublic: 'Công khai',
    resumesSearch: 'Tìm tên, email, vị trí...',
    resumesFilterAll: 'Tất cả',
    resumesFilterPublic: 'Công khai',
    resumesFilterPrivate: 'Riêng tư',
    resumesDownloadCsv: 'Tải CSV',
    resumesName: 'Tên',
    resumesEmail: 'Email',
    resumesPosition: 'Vị trí',
    resumesYoe: 'Kinh nghiệm',
    resumesLocation: 'Địa điểm',
    resumesUniversity: 'Trường',
    resumesPublicLabel: 'Hiển thị',
    resumesFile: 'Tệp',
    resumesUpdated: 'Ngày cập nhật',
    resumesUnit: '',
    resumesNote: '* Tính theo người dùng (cùng một người tải lại vẫn tính là 1)',
    resumesLoading: 'Đang tải dữ liệu CV...',
    resumesEmpty: 'Chưa có người dùng nào đăng CV.',
    resumesNoMatch: 'Không có kết quả phù hợp.',
    retention: 'Giữ chân',
    retentionLoading: 'Đang tải dữ liệu giữ chân...',
    retentionEmpty: 'Không có dữ liệu giữ chân.',
    retentionTotal: 'Tổng người dùng',
    retentionWAU: 'WAU (7 ngày)',
    retentionMAU: 'MAU (30 ngày)',
    retentionCohort: 'Giữ chân theo cohort tuần',
    retentionWeek: 'Tuần đăng ký',
    retentionUsers: 'Người đăng ký',
    retentionNote: '* Dựa trên last_sign_in_at. Tỷ lệ người dùng đăng nhập lại sau N tuần kể từ khi đăng ký.',
  },
}

export const METRICS_BASE = [
  { key: 'sessions', dataKey: 'sessions', color: '#2563EB', summaryKey: 'totalSessions', section: 'basic', tier: 'primary' },
  { key: 'signups', dataKey: 'signups', color: '#F59E0B', summaryKey: 'totalSignups', section: 'basic', tier: 'primary' },
  { key: 'resumeUploads', dataKey: 'resumeUploads', color: '#14B8A6', summaryKey: 'totalResumeUploads', section: 'basic', tier: 'primary' },
  { key: 'submissions', dataKey: 'submissions', color: '#374151', summaryKey: 'totalSubmissions', section: 'basic', tier: 'secondary' },
  { key: 'ad', dataKey: 'ad', color: '#4F46E5', summaryKey: 'adSubmissions', section: 'basic', tier: 'secondary' },
  { key: 'organic', dataKey: 'organic', color: '#10B981', summaryKey: 'organicSubmissions', section: 'basic', tier: 'secondary' },
  { key: 'companies', dataKey: 'companies', color: '#6B7280', summaryKey: 'uniqueCompanies', section: 'basic', tier: 'secondary' },
  { key: 'jobClicks', dataKey: 'jobClicks', color: '#F97316', summaryKey: 'totalJobClicks', section: 'talent', tier: 'primary' },
  { key: 'jobsPageViews', dataKey: 'jobsPageViews', color: '#06B6D4', summaryKey: 'totalJobsPageViews', section: 'talent', tier: 'primary' },
  { key: 'cardClicks', dataKey: 'cardClicks', color: '#EC4899', summaryKey: 'totalCardClicks', section: 'talent', tier: 'primary' },
  { key: 'applyClicks', dataKey: 'applyClicks', color: '#D946EF', summaryKey: 'totalApplyClicks', section: 'talent', tier: 'primary' },
  { key: 'jobApps', dataKey: 'jobApps', color: '#EF4444', summaryKey: 'totalJobApps', section: 'talent', tier: 'primary' },
  { key: 'jobAppsCompany', dataKey: 'jobAppsCompany', color: '#1D4ED8', summaryKey: 'totalJobAppsCompany', section: 'talent', tier: 'secondary' },
  { key: 'cvSuccessApps', dataKey: 'cvSuccessApps', color: '#059669', summaryKey: 'totalCvSuccessApps', section: 'talent', tier: 'secondary' },
  { key: 'saveClicks', dataKey: 'saveClicks', color: '#F472B6', summaryKey: 'totalSaveClicks', section: 'talent', tier: 'primary' },
  { key: 'resumePublic', dataKey: 'resumePublic', color: '#0D9488', summaryKey: 'totalResumePublic', section: 'talent', tier: 'secondary' },
  { key: 'resumePublicApp', dataKey: 'resumePublicApp', color: '#22C55E', summaryKey: 'totalResumePublicApp', section: 'talent', tier: 'secondary' },
  { key: 'resumePublicWeb', dataKey: 'resumePublicWeb', color: '#0EA5E9', summaryKey: 'totalResumePublicWeb', section: 'talent', tier: 'secondary' },
]

export const EXP_COLORS = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4', '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F']

export const DATA_KEYS = ['sessions', 'submissions', 'ad', 'organic', 'signups', 'companies', 'jobApps', 'jobClicks', 'cardClicks', 'jobsPageViews', 'applyClicks', 'saveClicks', 'resumeUploads', 'resumePublic', 'resumePublicApp', 'resumePublicWeb']

export const FUNNEL_TRACKING_START = '2026-05-09'

export const PRESET_FUNNELS = {
  ko: [
    { name: '대표 퍼널', desc: '세션 → 제출 → 가입 → 지원', keys: ['sessions', 'submissions', 'signups', 'jobApps'], since: FUNNEL_TRACKING_START },
  ],
  en: [
    { name: 'Main Funnel', desc: 'Session → Subs → Signin → Apply', keys: ['sessions', 'submissions', 'signups', 'jobApps'], since: FUNNEL_TRACKING_START },
  ],
  vi: [
    { name: 'Phễu chính', desc: 'Phiên → Gửi → Đăng ký → Ứng tuyển', keys: ['sessions', 'submissions', 'signups', 'jobApps'], since: FUNNEL_TRACKING_START },
  ],
}

export const MAX_BAR_HEIGHT = 160

export const STATUS_OPTIONS = ['applied', 'viewed', 'reviewing', 'docs_passed', 'interview', 'accepted', 'rejected']

export const STATUS_COLORS = {
  applied: { bg: '#E0E7FF', color: '#3730A3' },
  viewed: { bg: '#FEF3C7', color: '#92400E' },
  reviewing: { bg: '#DBEAFE', color: '#1E40AF' },
  accepted: { bg: '#D1FAE5', color: '#065F46' },
  rejected: { bg: '#FEE2E2', color: '#991B1B' },
}

export const HR_STATUS_COLORS = {
  pending: { bg: '#FEF3C7', color: '#92400E', label: { ko: '미입력', en: 'Pending', vi: 'Chưa nhập' } },
  submitted: { bg: '#DBEAFE', color: '#1E40AF', label: { ko: '승인 대기', en: 'Submitted', vi: 'Chờ duyệt' } },
  approved: { bg: '#D1FAE5', color: '#065F46', label: { ko: '승인됨', en: 'Approved', vi: 'Đã duyệt' } },
  rejected: { bg: '#FEE2E2', color: '#991B1B', label: { ko: '반려', en: 'Rejected', vi: 'Từ chối' } },
}

export const COLORS = ['#4F46E5', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#6B7280']

export const inputStyle = {
  padding: '6px 10px', border: '1px solid #d1d5db', borderRadius: 6, fontSize: 13,
}

export const sectionStyle = {
  background: '#fff', border: '1px solid #e5e7eb', borderRadius: 12, padding: 20, marginBottom: 24,
}

export const sectionTitle = {
  fontSize: 16, fontWeight: 600, margin: '0 0 16px 0',
}
